feat: add animal commands
skyra-project/artiel pull request #109
Opened 2024-01-26 23:42 UTC by OfficialSirH

Adds animal commands from skyra

2024-01-26 23:51 UTC, favna submitted a review, later dismissed

2024-01-26 23:51 UTC, favna commented on src/locales/en-US/commands/fox.json
> +	"description": "a random image of a fox",
What does the fox say

2024-01-27 09:04 UTC, kyranet requested changes

2024-01-27 10:56 UTC, kyranet submitted a review, later dismissed

2024-01-27 21:13 UTC, kyranet approved these changes

2024-01-28 09:10 UTC, merged