feat: add feed command for feeding users
skyra-project/artiel pull request #180
Opened 2024-09-05 10:09 UTC by Swiizyy

Close: #9

2024-09-05 19:40 UTC, favna approved these changes

2024-09-06 18:47 UTC, favna submitted a review, later dismissed

2024-09-10 07:52 UTC, kyranet requested changes

2024-09-10 07:52 UTC, kyranet commented on src/commands/feed.ts
> +		const url = new URL(`https://foodish-api.com/api/images/${options.type}`);
You forgot this line:
```suggestion
		const url = new URL(`https://foodish-api.com/api/images/${type}`);
```

2024-09-10 08:46 UTC, kyranet approved these changes

2024-09-10 08:48 UTC, merged